---
title: "2021 FHB Pipeline Automatic Image Annotation vs. Manual Image Annotation - Inter Rater Reliability; Spike"
author: "Julian Cooper"
date: "2023-10-03"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

# Overview

Compare manual image annotation (MIA) - inter rater reliability (IRR)
disease results on a single spike basis to automatic image annotation
(AIA) pipeline inferences on the same spikes. 

# Load Libraries
```{r,print = FALSE}

library(ggplot2) # For plotting data
library(tidyverse) # For manipulating/analyzing data
library(stringr) # For regex
library(GGally) # For ggcor
library(irr) # For calculating ICC
library(ggridges)    # for making ridge plot
library(viridis)     # color scaling in plot
library(rmarkdown) # For formatting rmarkdown
library(reshape2) # For reshaping correlation matrix

```

# Compare Model Spike Disease Prediction to IRR Spike Disease Annotation
Not filtering for gradability
```{r}

# Load pipeline inferences on IRR images
aia_IRR <- read.csv("/Users/jcooper/Desktop/thesis_research/fhb_mineral/FHB_phenotyping_pipeline/automatic_image_annotation/2021model/raw_data/results_summary_v1-icc-icc_model_2021_vertical.csv")

# Count gradable vs nongradable
aia_IRR %>%
  filter(gradability_prob <= 0.50) %>%
  count()


# Convert pipeline image path to MIA IRR format
aia_IRR$img_name <- gsub(".*/icc_wheat_v1_final/(.*?)\\.png", "\\1", as.character(aia_IRR$img_path))

# Trim and format df
aia <- aia_IRR[, c(7, 14)] # Keep FHB, image name
colnames(aia)[1] <- "AIA_FHB"

# Load IRR DF
irr <- read.csv("/Users/jcooper/Desktop/thesis_research/fhb_mineral/FHB_phenotyping_pipeline/manual_image_annotation/inter_rater_reliability_annotations/data/2022/wheat2022_mia_inter_rater_reliabilit.csv")
irr <- irr %>%
  dplyr::select(-c(2:6)) # keep image name and disease anotations from Raters A-E

# Merge AIA and IRR DF
aia_irr_intersect <- merge(aia, irr, by = c("img_name"))

# Change Location names to match abbreviations
aia_irr_intersect <- aia_irr_intersect %>%
  mutate(Location = substr(img_name, 12, 12),  # Extract the 12th character, S for Saint_Paul or C for Crookston
         Location = ifelse(Location == "S", "StP",      # Conditionally replace 'S' with 'StP'
                           ifelse(Location == "C", "Crk", Location)))   # Conditionally replace 'C' with 'Crk'

# Average spike disease in AIA and IRR (average of all 5 raters on same spike)
aia_irr_intersect %>%
  na.omit() %>% 
  mutate(irr_spike_avg = (A + B + C + D +E)/5) %>%
  summarise(mean(AIA_FHB),
            mean(irr_spike_avg))

# Average spike disease in AIA and IRR (average of all 5 raters on same spike), by location
aia_irr_intersect %>%
  na.omit() %>% 
  mutate(irr_spike_avg = (A + B + C + D +E)/5) %>%
  group_by(Location) %>%
  summarise(mean(AIA_FHB),
            mean(irr_spike_avg))

# Plot AIA vs IRR spike disease, color by location
aia_irr_intersect_scatterplot <-aia_irr_intersect %>%
  na.omit() %>% 
  mutate(irr_spike_avg = (A + B + C + D +E)/5) %>%
  ggplot(aes(x = irr_spike_avg, y = AIA_FHB, color = Location)) +
  geom_point(size = .5) +
  geom_smooth(method = "lm", se = FALSE, color = "blue") + # Add linear regression line 
  geom_abline() + 
  theme_classic()
print(aia_irr_intersect_scatterplot)
ggsave("/Users/jcooper/Desktop/thesis_research/fhb_mineral/FHB_phenotyping_pipeline/automatic_image_annotation/2021model/aia_mia_irr_spike/results/aia_irr_spike_scatterplot.png",
plot = aia_irr_intersect_scatterplot, width = 6, height = 4)

# Plot AIA vs IRR spike disease, color by location, facet by rater
aia_irr_intersect_scatterplot_rater <- aia_irr_intersect %>%
  pivot_longer(cols = 3:7, names_to = "Rater", values_to = "FHB") %>%
  ggplot(aes(x = FHB, y = AIA_FHB, color = Location)) +
  geom_point(size = .5) +
  geom_smooth(method = "lm", se = FALSE, color = "blue") + # Add linear regression line 
  geom_abline() + 
  theme_classic() +
  facet_grid(~Rater)
print(aia_irr_intersect_scatterplot_rater)
ggsave("/Users/jcooper/Desktop/thesis_research/fhb_mineral/FHB_phenotyping_pipeline/automatic_image_annotation/2021model/aia_mia_irr_spike/results/aia_irr_spike_scatterplot_rater.png",
plot = aia_irr_intersect_scatterplot_rater, width = 6, height = 4)

# Pairwise Pearson correlations
# Trim df to create matrix of raters and pipeline disease scores
aia_irr_trim <- aia_irr_intersect[,2:7] 

# Calculate correlation table
corr <- round(cor(aia_irr_trim, use="complete.obs"), 2)

# Get upper triangle of the correlation matrix
  get_upper_tri <- function(cormat){
    cormat[lower.tri(cormat)]<- NA
    return(cormat)
  }
upper_tri <- get_upper_tri(corr)

# Reshape correlation matrix
cor_melted <- melt(upper_tri)

# Plot matrix
irr_rating_correlation <- ggplot(data = cor_melted, aes(Var2, Var1, fill = value)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white",
                       midpoint = 0, na.value = "white", limit = c(-1, 1), space = "Lab",
                       name = "Pearson\nCorrelation") +
  coord_fixed() +
  geom_text(aes(label = ifelse(!is.na(value), sprintf("%.2f", value), "")),
            color = "black", size = 2.88) +  # Make NA boxes white
  theme_classic() +
  labs(x = "Rater") +
  theme(
    axis.title.y = element_blank(),
    panel.grid.major = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "none",
  ) +
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                               title.position = "top", title.hjust = 0.5)) +
  theme(text=element_text(size=8, family = "Helvetica"),
        plot.margin = margin(t = 0,  # Top margin
                             r = 0,  # Right margin
                             b = 0,  # Bottom margin
                             l = 0)) # Left margin)

print(irr_rating_correlation)
ggsave("/Users/jcooper/Desktop/thesis_research/fhb_mineral/FHB_phenotyping_pipeline/automatic_image_annotation/2021model/aia_mia_irr_spike/results/aia_irr_rating_correlation.png", plot = irr_rating_correlation, height = 5, width = 5)

# Correlation between AIA and IRR spike disease for each rater
aia_irr_intersect %>%
  pivot_longer(cols = 3:7, names_to = "Rater_ID", values_to = "FHB") %>%
  group_by(Rater_ID) %>% 
  na.omit() %>%
  summarise(cor(AIA_FHB, FHB))

# Intra class correlation between AIA and IRR
# ICC between AIA - IRR
aia_irr_intersect_trim <- aia_irr_intersect[,c(2:7)] # Trim DF
icc_result <- icc(aia_irr_intersect_trim, model = "oneway", type = "agreement", unit = "single")
print(icc_result)

# ICC between Crk AIA - IRR
icc_crk <- aia_irr_intersect %>%
  filter(Location == "Crk")
icc_crk_trim <- icc_crk[,c(2:7)]
print(icc(icc_crk_trim, model = "oneway", type = "agreement", unit = "single"))

# ICC between StP AIA - IRR
icc_stp <- aia_irr_intersect %>%
  filter(Location == "StP")
icc_stp_trim <- icc_stp[,c(2:7)]
print(icc(icc_stp_trim, model = "oneway", type = "agreement", unit = "single"))



```